### ISSUE TITLE
Configuration for base 16 colors

### ISSUE THREAD

**Issue by HalosGhost** [tomszilagyi/zutty#11]
Do you have any interest / intention in allowing the basic 16 colors to be configurable?

Having foreground/background configurable is already a good step towards this, but most (all?) TEs I've used and seen support theming via configuration of these basic colors. I cannot speak for most users, but I would love to be able to keep my basic color scheme as I try to switch to Zutty for some more thorough testing. ☺

**Comment by tomszilagyi** [comment]
This is going to be done at some point (low prio), maybe you want to come up with a PR to support the requisite control sequences?

**Comment by MathGeniusJodie** [comment]
what about the escape sequences that work in the linux virtual console? does it need to be a setting?
`printf "
\e]P02b303b
\e]P1bf616a
\e]P2a3be8c
\e]P3ebcb8b
\e]P48fa1b3
\e]P5b48ead
\e]P696b5b4
\e]P7c0c5ce
\e]P865737e
\e]P9bf616a
\e]PAa3be8c
\e]PBebcb8b
\e]PC8fa1b3
\e]PDb48ead
\e]PE96b5b4
\e]PFeff1f5
"`

**Comment by tomszilagyi** [comment]
@HalosGhost For personal evaluation purposes, it is probably easiest if you just change the hardcoded palette colors and recompile (look for `makePalette256` in vterm.cc).

@MathGeniusJodie I don't think those sequences are supported by xterm (correct me if I'm wrong), they are broken design and not part of any standard (correct me if I'm wrong), so I don't think Zutty should support them either. See https://invisible-island.net/xterm/manpage/xterm.html#VT100-Widget-Resources:brokenLinuxOSC -- I would prefer not to go into that swamp. (Whether we need to support a similar workaround remains to be seen. Zutty has a (fairly large) safety limit on unterminated OSC commands.)

I am also not really a fan of adding resource settings for palette colors, xterm has problems with that -- apparently X libraries have hard limits on the number of resources and will crash if you breach the limit (see e.g., `color255` in xterm's manpage). That only becomes an acute problem if resources are generated for all colors (not just the first 16), but I also want to avoid bloating the command line options (Zutty has a duality of command line options and X resource settings, and I want to keep that).

What I would see as a welcome addition is support for the `OSC 4` sequence for setting/querying colors of the palette. I believe this is standardized by ECMA-48. In xterm I can do this to query the first 16 colors (but can be extended up to 255):

```
$ for c in {0..15}; do printf "\ncolor $c = \e]4;$c;?\e\\"; sleep 0.1; done;

color 0 = ^[]4;0;rgb:0000/0000/0000^[\
color 1 = ^[]4;1;rgb:cdcd/0000/0000^[\
color 2 = ^[]4;2;rgb:0000/cdcd/0000^[\
color 3 = ^[]4;3;rgb:cdcd/cdcd/0000^[\
color 4 = ^[]4;4;rgb:0000/0000/eeee^[\
color 5 = ^[]4;5;rgb:cdcd/0000/cdcd^[\
color 6 = ^[]4;6;rgb:0000/cdcd/cdcd^[\
color 7 = ^[]4;7;rgb:e5e5/e5e5/e5e5^[\
color 8 = ^[]4;8;rgb:7f7f/7f7f/7f7f^[\
color 9 = ^[]4;9;rgb:ffff/0000/0000^[\
color 10 = ^[]4;10;rgb:0000/ffff/0000^[\
color 11 = ^[]4;11;rgb:ffff/ffff/0000^[\
color 12 = ^[]4;12;rgb:5c5c/5c5c/ffff^[\
color 13 = ^[]4;13;rgb:ffff/0000/ffff^[\
color 14 = ^[]4;14;rgb:0000/ffff/ffff^[\
color 15 = ^[]4;15;rgb:ffff/ffff/ffff^[\
```
xterm answers the query with the escape sequence that would set the color to its current value, which is neat. (Note the output has 16 bits per component, we do not want to replicate this, since we have 24-bit colors.)

To set e.g., color 9 (normally bright red) to some light shade of blue:
```
$ printf "\e]4;9;#00cafe\e\\"
```

It should also be possible to query/set more than one color, by suppying multiple pairs of color number and spec:

```
$ printf "\e]4;1;#ff4488;3;#dedbef;9;#0babe0\e\\"
~$ printf "\e]4;1;?;3;?;9;?\e\\"
^[]4;1;rgb:ffff/4444/8888^[\^[]4;3;rgb:dede/dbdb/efef^[\^[]4;9;rgb:0b0b/abab/e0e0^[\
```

Finally, the `OSC 104` sequence resets one or more palette entries to their default color values (or, if no color numbers are given, resets the entire palette). This needs to be supported as well. E.g., to reset the colors above to their original values:

```
printf "\e]104;1;3;9\e\\"
```
To reset the complete palette:

```
printf "\e]104\e\\"
```

In xterm, if the color of a palette entry changes, that will be immediately reflected on the screen (if there is visible text with that color). This can be replicated (but I don't necessarily think we need to do so); it would require a scan of all cells for RGB values matching the old values and substituting them with the new value. There is an inherent ambiguity there: if the color of a cell was set by other means (SGR 38/48) to the same (old) value, that should not be changed, but we have no way to discriminate that. I think it's ok if a palette change only affects new output, as users/programs usually set up their palette first and generate screen output afterwards (but feel free to disagree with me).

**Comment by MathGeniusJodie** [comment]
this is a very exciting development, I'm really looking forward to finally using a terminal emulator made in this century, I'm still using xterm, and this is the one feature zutty is missing

**Comment by MathGeniusJodie** [comment]
my body is ready 
```sh
# ocean.dark
# generated by terminal.sexy
printf "\e]4;0;#2b303b\e\\"
printf "\e]4;1;#bf616a\e\\"
printf "\e]4;2;#a3be8c\e\\"
printf "\e]4;3;#ebcb8b\e\\"
printf "\e]4;4;#8fa1b3\e\\"
printf "\e]4;5;#b48ead\e\\"
printf "\e]4;6;#96b5b4\e\\"
printf "\e]4;7;#c0c5ce\e\\"
printf "\e]4;8;#65737e\e\\"
printf "\e]4;9;#bf616a\e\\"
printf "\e]4;10;#a3be8c\e\\"
printf "\e]4;11;#ebcb8b\e\\"
printf "\e]4;12;#8fa1b3\e\\"
printf "\e]4;13;#b48ead\e\\"
printf "\e]4;14;#96b5b4\e\\"
printf "\e]4;15;#eff1f5\e\\"
```

**Comment by tomszilagyi** [comment]
Feel free to work on a PR, this is a good "first issue" for someone that wants to contribute to the development of Zutty.

**Comment by tomszilagyi** [comment]
I decided to go for providing extra resources (not configurable via the command line). This breaks the symmetry, but turned out to be quite non-intrusive to implement, and I believe it provides a more user-friendly interface than using escape sequences. (Those might turn out to be useful, if there is a valid use case for dynamically reconfiguring palette colors, but not on the roadmap for now.)

@MathGeniusJodie put this in your ~/.Xresources instead:
```
Zutty.color0:   #2b303b
Zutty.color1:   #bf616a
Zutty.color2:   #a3be8c
Zutty.color3:   #ebcb8b
Zutty.color4:   #8fa1b3
Zutty.color5:   #b48ead
Zutty.color6:   #96b5b4
Zutty.color7:   #c0c5ce
Zutty.color8:   #65737e
Zutty.color9:   #bf616a
Zutty.color10:  #a3be8c
Zutty.color11:  #ebcb8b
Zutty.color12:  #8fa1b3
Zutty.color13:  #b48ead
Zutty.color14:  #96b5b4
Zutty.color15:  #eff1f5
```
