### ISSUE TITLE
Feature request: configurable to start zutty maximised

### ISSUE THREAD

**Issue by paulie-g** [tomszilagyi/zutty#21]
I'm currently doing this via my WM (openbox) and have set the required geometry, but it would be nice to have this as a command line/config parameter.

**Comment by tomszilagyi** [comment]
TBH, doing it via the WM is exactly the right approach, and I do not see a reason to add the complexity of handling this to any single client. The WM has (or should have) suitable controls/shortcuts to allow the user to easily act on already visible windows, or have policies to have certain app windows maximized on creation. Yes, certain clients have options to _request_ being maximized by the WM (e.g., xterm has `-maximized`), but the authority of granting/denying that request nevertheless lies with the WM. (Case in point: `-maximized` has no effect when passed to xterm, because my tiling window manager will ignore it, as expected.)
