### ISSUE TITLE
set mode 7 and reset mode 7

### ISSUE THREAD

**Issue by xyproto** [tomszilagyi/zutty#25]
Hi,

I've made a small editor named [`o`](https://github.com/xyproto/o). Some terminal emulators struggle a bit when using arrow up and arrow down to go up and down one line, and pressing `ctrl-n` and `ctrl-p` to go up and down 10 lines. But not Zutty! Zutty works great and has excellent performance.

However, I get quite a few of these messages when running `o`:

```
W [vterm.icc:1366] (Unimplemented) set mode 7
W [vterm.icc:1387] (Unimplemented) reset mode 7
```

I'm not 100% sure if this is just `o` sending terminal codes that it does not need to send, or if these would be nice to have implemented.

This is a feature request for implementing these.

Thanks for creating Zutty.

(I also maintain the Arch Linux AUR packages named `zutty` and `zutty-git` and are considering moving `zutty` to `[community]`, making it an official package).

**Comment by tomszilagyi** [comment]
Hi,

I'm glad you like Zutty so far. Regarding the `(Unimplemented)` notices you are getting, I was not able to dig up any info on what the mode number 7 might be. The definitive reference for me is [xterm](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html), if you visit that link and search for `CSI Pm h` you will see that modes 2, 4, 12 and 20 are known and handled by xterm (2 is not handled by Zutty at the moment, the others are). I have also checked the DEC manuals for VT220 and VT520, they also do not mention anything else.

If you find out what the mode number 7 is, I am happy to take a look, but otherwise I would say that it's a puzzle best tackled by debugging the application and finding out why it is sending meaningless stuff to the terminal. One hunch I have is that there is a typo somewhere and it means to send `CSI ? Pm h` instead (with Pm = 7), that is DECSET mode 7, which *is* defined and controls auto linewrap mode (DECAWM).

**Comment by xyproto** [comment]
According to this VT100 overview, "Enable Line Wrap" is `<ESC>[7h`.

If I `echo -e '\033[7h'` in ie. `gnome-terminal` or `alacritty`, I can't see any complains. However, `st` also complains that `erresc: unknown set/reset mode 7`.

Is this specific to the VT100 codes, or am I testing this the wrong way?

**Comment by tomszilagyi** [comment]
The linked overview is obviously wrong, the correct sequence for enabling/disabling linewraps is `CSI ? 7 h/l`, so e.g., `printf "\e[?7h"` will disable it (it's enabled by default). Look at some real documentation instead, like [this](https://vt100.net/docs/vt220-rm/chapter4.html#S4.6.14).

Just because other terminals don't complain does not mean that it's right. You can test whether they actually react by sending the sequence to disable line wrap and then typing on the command line past the right margin. If the sequence did turn off auto-wrap mode, then wrap-around will happen in the same line (overwriting the beginning), or you won't get any wrap-around at all. In xterm, this happens with the correct sequence (containing `?`) but not with the one without `?` which is ignored by xterm.

**Comment by xyproto** [comment]
Thank you! I wondered why I got weird results. I didn't even consider that the documentation I found was wrong.

`printf "\e[?7l"` certainly works as you describe. I'll correct the little editor I wrote.

**Comment by xyproto** [comment]
zutty is now in Arch, btw
