### ISSUE TITLE
waf install: broken rev deps

### ISSUE THREAD

**Issue by gregwebs** [tomszilagyi/zutty#27]
I wanted to install zutty. I was able to apt install the libs so that ./waf configure succeeds. However, when I compile/install it fails:

```
Waf: Leaving directory `/tmp/zutty-0.8/build'
Broken revdeps detected on {
	{task 139733974599944: cxxprogram charvdev.cc.1.o,font.cc.1.o,fontpack.cc.1.o,frame.cc.1.o,gl.cc.1.o,log.cc.1.o,main.cc.1.o,options.cc.1.o,pty.cc.1.o,renderer.cc.1.o,selmgr.cc.1.o,vterm.cc.1.o -> zutty},
	{task 139733974600056: inst zutty -> zutty}}
```

I am not familiar with waf. I would prefer to install zutty via a package manager or to compile a binary via a reproducible environment such as a docker container.

**Comment by tomszilagyi** [comment]
Please post the complete console output you are getting; the broken revdeps are a symptom, rather than the root cause. Could be helpful if you posted the complete output of the configure step as well.

Please specify the exact version of Zutty that you are trying to build. Commit hash is preferred.

Please specify some basic data about where you are trying to compile zutty, i.e., distro/version.

As a final note, you should suggest to your distribution that they package Zutty if you think it would be worth making it available to many users.

**Comment by gregwebs** [comment]
Yeah, it looks like the Broken revdeps output is distracting. I am trying to give the viewpoint of someone trying to install this project. It is likely that zutty will remain relatively unknown until it can be installed without installing supporting libraries and compilers :(

I switched from g++ version 5 to g++ version 7 and now it compiles. Maybe `./waf configure` could require a greater version of g++?

**Comment by tomszilagyi** [comment]
Yeah, modern C++ programs usually need a relatively modern compiler. I do compile Zutty with g++ 6.3, which is the one that comes with Debian *oldstable*. ;)

Thanks for trying Zutty.
