### ISSUE TITLE
make_x_window assertion failed

### ISSUE THREAD

**Issue by chybz** [tomszilagyi/zutty#3]
Hi there !
While trying out Zutty on Debian bullseye, the following assertion occurs.

```
$ zutty -verbose
Zutty 0.6-8-gc792cf1
Copyright (C) 2020 Tom Szilagyi

This program comes with ABSOLUTELY NO WARRANTY.
Zutty is free software, and you are welcome to redistribute it
under the terms and conditions of the GNU GPL v3 (or later).

I [font.cc: 54] Loading /usr/share/fonts/X11/misc/9x18.pcf.gz as primary
I [font.cc:198] Glyph size 9x18
I [font.cc: 54] Loading /usr/share/fonts/X11/misc/9x18B.pcf.gz as overlay
I [font.cc:198] Glyph size 9x18
I [main.cc:120] Window ID: 60817410 / 0x3a00002
zutty: ../src/main.cc:174: void make_x_window(Display*, EGLDisplay, const char*, int, int, Window*, void**, void**): Assertion `val == 2' failed.
Aborted
```

How can I help resolve this ?

**Comment by tomszilagyi** [comment]
Hi!

Thanks for trying Zutty!

The error is due to a difference in EGL client library version from what the code expects [ref: https://www.khronos.org/registry/EGL/sdk/docs/man/html/eglQueryContext.xhtml (look for `EGL_CONTEXT_CLIENT_VERSION`)]

If you comment out (or remove) line 174 of main.cc that says `assert (val == 2);` and recompile, do you get a different error or does the program appear to work normally?

If it does work normally, can you change the assert to a printout on `val` and report what is the actual value you have there?

Also, what is your egl client library version (`dpkg -l | grep libegl`)? I have `libegl1 1.3.2-1` and `libegl-dev 1.3.2-1` on my Debian Bullseye and it works.

Thanks!

**Comment by chybz** [comment]
When I saw "old bitmap fonts", I was like "take my money !"...

`val` is `3` here, and removing the `assert` let Zutty launch properly.

As for `libegl`, I also have `1.3.2-1`, but I had to install a fairly recent NVIDIA (460.27.04-1) driver from experimental due to some major issues with Wayland.

Thanks !

(see you in another issue, I have a segfault for you)

**Comment by tomszilagyi** [comment]
Thanks for the feedback!

Will update that assert to make it more permissive (or remove it entirely) & close this issue when the change has landed in master.

**Comment by tomszilagyi** [comment]
Could you possibly check if this version of the code works for you:

```
   // test eglQueryContext()
   {
      EGLint val;
      eglQueryContext (egl_dpy, ctx, EGL_CONTEXT_CLIENT_TYPE, &val);
      assert (val == EGL_OPENGL_ES_API);
   }
```
I.e., change `EGL_CONTEXT_CLIENT_VERSION` to `EGL_CONTEXT_CLIENT_TYPE`, and `2` to `EGL_OPENGL_ES_API` and test if the assert bombs or not.

(If it returns something other than expected, I will remove the check completely, but it would be nice to have some idea whether the EGL context is ok or not, before going further in the program.)

Thanks!

**Comment by chybz** [comment]
Works fine, thanks !
What do you think about not printing an error in this case (E [main.cc:979] Error: fatal IO error 11 (Resource temporarily unavailable) on X server :1) ? Maybe could you detect the close action ?

**Comment by tomszilagyi** [comment]
Excellent, will be part of my upcoming batch of fixes (hopefully over the weekend).
Thanks for reporting and testing!
