### ISSUE TITLE
illegal hardware instruction (core dumped)

### ISSUE THREAD

**Issue by chromer030** [tomszilagyi/zutty#30]
Hi, I installed latest version (0.8) from Arch Linux repository (https://archlinux.org/packages/community/x86_64/zutty/) , but it wont run and led to this error :
````
zsh: illegal hardware instruction (core dumped)
````

Arch Linux
Kernel : 5.11.11
Desktop : KDE Plasma 5.21.4 (X server)
CPU : Intel i3 4150
RAM : 8 GB DDR3
GPU : amd radeon ( opengl 3.3)

**Comment by tomszilagyi** [comment]
Hi,

Please report this against the Arch Linux package, or reproduce it with a binary of Zutty that you compiled yourself.

This is just speculation on my part, because I don't know how the Arch Linux package is made, but I think the problem *might* be that Arch Linux compiles a binary of Zutty using its build script out of the box, which includes compiler options `-march=native` and `-mtune=native`. Anyone wishing to create binaries for wider circulation / distribution should replace those with suitable downgrades so the binary is portable.

**Comment by chromer030** [comment]
Thank you very much for explanation, i will report it on Arch Bugs and reference it to this issue.

**Comment by Scimmia22** [comment]
Better yet, the build system shouldn't override CFLAGS/CXXFLAGS

**Comment by chromer030** [comment]
Fixed.
