### ISSUE TITLE
High Xorg CPU usage with zutty

### ISSUE THREAD

**Issue by brandoninvergo** [tomszilagyi/zutty#38]
I apologize in advance for the low quality of this report. I'm not sure where to begin digging. Please let me know what information would help in identifying the problem.

I recently started using zutty instead of xterm. I notice that when I open zutty, the CPU usage of the Xorg process and that of my window manager (stumpwm) each go up to about 70% as reported by `htop`. If I close zutty and open xterm, the problem does not occur.

I'm running zutty 0.9 on Arch Linux (installed as usual from the `community` repository).

My zutty-related settings in `.Xresources` are:
```
Zutty.altScroll: true
Zutty.font: SourceCodePro
Zutty.fontsize: 12
Zutty.bg: #324150
Zutty.fg: #c0c7ce
Zutty.cr: #c0c7ce
Zutty.boldColors: true
```
`zutty -glinfo` gives:
```
EGL_VERSION     = 1.5
EGL_VENDOR      = Mesa Project
EGL_EXTENSIONS  = EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_CHROMIUM_sync_control EGL_EXT_buffer_age EGL_EXT_create_context_robustness EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_EXT_swap_buffers_with_damage EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_KHR_swap_buffers_with_damage EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver EGL_NOK_texture_from_pixmap EGL_WL_bind_wayland_display
EGL_CLIENT_APIS = OpenGL OpenGL_ES

GL_RENDERER     = Radeon RX Vega (VEGA10, DRM 3.40.0, 5.12.2-arch1-1, LLVM 11.1.0)
GL_VERSION      = OpenGL ES 3.2 Mesa 21.1.0
GL_VENDOR       = AMD
GL_EXTENSIONS   = GL_EXT_blend_minmax GL_EXT_multi_draw_arrays GL_EXT_texture_filter_anisotropic GL_EXT_texture_compression_s3tc GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_format_BGRA8888 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_stencil8 GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_EXT_draw_instanced GL_EXT_texture_sRGB_decode GL_OES_EGL_image GL_OES_depth_texture GL_AMD_performance_monitor GL_OES_packed_depth_stencil GL_EXT_texture_type_2_10_10_10_REV GL_NV_conditional_render GL_OES_get_program_binary GL_APPLE_texture_max_level GL_EXT_discard_framebuffer GL_EXT_read_format_bgra GL_EXT_frag_depth GL_NV_fbo_color_attachments GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_array_object GL_OES_viewport_array GL_ANGLE_pack_reverse_row_order GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_EXT_occlusion_query_boolean GL_EXT_robustness GL_EXT_texture_rg GL_EXT_unpack_subimage GL_NV_draw_buffers GL_NV_read_buffer GL_NV_read_depth GL_NV_read_depth_stencil GL_NV_read_stencil GL_EXT_draw_buffers GL_EXT_map_buffer_range GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_NV_pixel_buffer_object GL_OES_depth_texture_cube_map GL_OES_required_internalformat GL_OES_surfaceless_context GL_EXT_color_buffer_float GL_EXT_sRGB_write_control GL_EXT_separate_shader_objects GL_EXT_shader_group_vote GL_EXT_shader_implicit_conversions GL_EXT_shader_integer_mix GL_EXT_tessellation_point_size GL_EXT_tessellation_shader GL_ANDROID_extension_pack_es31a GL_EXT_base_instance GL_EXT_compressed_ETC1_RGB8_sub_texture GL_EXT_copy_image GL_EXT_draw_buffers_indexed GL_EXT_draw_elements_base_vertex GL_EXT_gpu_shader5 GL_EXT_polygon_offset_clamp GL_EXT_primitive_bounding_box GL_EXT_render_snorm GL_EXT_shader_io_blocks GL_EXT_texture_border_clamp GL_EXT_texture_buffer GL_EXT_texture_cube_map_array GL_EXT_texture_norm16 GL_EXT_texture_view GL_KHR_blend_equation_advanced GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_NV_image_formats GL_OES_copy_image GL_OES_draw_buffers_indexed GL_OES_draw_elements_base_vertex GL_OES_gpu_shader5 GL_OES_primitive_bounding_box GL_OES_sample_shading GL_OES_sample_variables GL_OES_shader_io_blocks GL_OES_shader_multisample_interpolation GL_OES_tessellation_point_size GL_OES_tessellation_shader GL_OES_texture_border_clamp GL_OES_texture_buffer GL_OES_texture_cube_map_array GL_OES_texture_stencil8 GL_OES_texture_storage_multisample_2d_array GL_OES_texture_view GL_EXT_blend_func_extended GL_EXT_buffer_storage GL_EXT_float_blend GL_EXT_geometry_point_size GL_EXT_geometry_shader GL_EXT_shader_samples_identical GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_OES_EGL_image_external_essl3 GL_OES_geometry_point_size GL_OES_geometry_shader GL_OES_shader_image_atomic GL_EXT_clip_cull_distance GL_EXT_disjoint_timer_query GL_EXT_texture_compression_s3tc_srgb GL_EXT_window_rectangles GL_MESA_shader_integer_functions GL_EXT_clip_control GL_EXT_color_buffer_half_float GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_semaphore GL_EXT_semaphore_fd GL_EXT_texture_compression_bptc GL_KHR_parallel_shader_compile GL_NV_alpha_to_coverage_dither_control GL_AMD_framebuffer_multisample_advanced GL_EXT_EGL_image_storage GL_EXT_texture_shadow_lod GL_INTEL_blackhole_render GL_MESA_framebuffer_flip_y GL_NV_compute_shader_derivatives GL_EXT_demote_to_helper_invocation GL_EXT_depth_clamp GL_EXT_texture_query_lod

Compute shader:
- max. global (total) work group counts: x=65535 y=65535 z=65535
- max. local (per-shader) work group sizes: x=1024 y=1024 z=1024
- max. local work group invocations: 1024
```

FWIW my default session when I launch the terminal loads up Screen with a few shells.

I understand that this paucity of information is probably not a lot to go by, so please let me know if there's anything else I can do to help figure out what's going on.

**Comment by tomszilagyi** [comment]
Hi,

Thank you for the report. Interesting phenomenon to investigate for sure. You could try a few things in an attempt to narrow it down.

Some ideas:
- Start zutty with a very simple program instead of a shell (that, as you mention, pulls in other stuff, like screen). For example, try running `zutty -e vmstat 1`.
- Start zutty without any of your customizations present in .Xresources (although I have a hard time imagining that any of your settings might be a problem).
- Try a different font -- most interesting would be to see if the problem persists with the default misc-fixed 9x18.
- Try a different window manager on your system with everything else intact.
- Try to compile zutty from source yourself (it's not very hard, even if you are not experienced doing such things).

Also, do I understand correctly that there is a constant ~70% CPU usage on your system coming from X and your WM each, but not zutty, as long as zutty is running? That sounds like an infinite loop of events generated by the WM somehow (putting load on the WM itself and X), but no idea really -- I would probably look into tracing the activity of those processes. What if there are two instances of zutty, do these figures double (or at least go up in a significant way) or is this constant?

**Comment by brandoninvergo** [comment]
Hi thanks for the input.

> Also, do I understand correctly that there is a constant ~70% CPU usage on your system coming from X and your WM each, but not zutty, as long as zutty is running?

That is correct, yes.

I have now tried zutty on the same system in LXQt/Openbox, Gnome/Wayland, and Gnome/Xorg and all of them were fine. So the problem seems to be just in StumpWM.

Back in StumpWM, I've tried `zutty -name foo -e vmstat 1` (setting `-name` as a cheap way to ignore my .Xresources settings) and the problem persists. The CPU usage does not scale with the number of zutty instances running.

So, I guess this might be a problem with the window manager instead. Looking at the window properties of an Xterm window vs a Zutty window, I see that Zutty has `_VARIABLE_REFRESH` set, whereas Xterm doesn't. That might be something for them to look into...anyway, presumably not Zutty's problem.

Anyway, I'll close this bug report for now unless there is evidence that Zutty is doing something wrong. Doesn't look like it though. Thanks for your patience!

**Comment by brandoninvergo** [comment]
Sorry, I think I had better let the maintainer close the issue! Bad manners.

**Comment by tomszilagyi** [comment]
Interesting findings, thanks for sharing!

I guess a logical next step could be testing StumpWM with another GPU-accelerated term (alacritty, kitty) to see if they provoke a similar problem.

**Comment by brandoninvergo** [comment]
I can confirm that neither alacritty nor kitty cause this problem.

**Comment by tomszilagyi** [comment]
After some analysis I believe that I understand the root cause of this.

When Zutty receives a Configure event (normally sent on geometry changes), it sets WM_NORMAL_HINTS to reflect its new size. The problem is, StumpWM seems to generate another Configure event (with the same size as before) in response to Zutty setting this property. Which leads to an infinite loop. Well, almost infinite -- after a (sometimes pretty long) while, it seems to stop eventually, suggesting that the behaviour of sending the extra Configure event (with an unchanged size) on an update of the WM_NORMAL_HINTS property is not fully deterministic.

I am not sure that this behaviour of StumpWM is an outright bug, but this is the first time I see Zutty getting multiple/redundant configure events without a size change (or, anything really, other than the program having called XSetWMNormalHints) to explain them.

The below trivial patch should fix the problem, feel free to test and confirm.

```
diff --git a/src/main.cc b/src/main.cc
index a1d72e9..cca015c 100644
--- a/src/main.cc
+++ b/src/main.cc
@@ -919,9 +919,13 @@ x11Event (XEvent& event, XIC& xic, int ptyFd, bool& destroyed, bool& holdPtyIn)
       break;
    case ConfigureNotify:
       vt->resize (event.xconfigure.width, event.xconfigure.height);
-      sizeHints.width = event.xconfigure.width;
-      sizeHints.height = event.xconfigure.height;
-      XSetWMNormalHints (xDisplay, xWindow, &sizeHints);
+      if (sizeHints.width != event.xconfigure.width ||
+          sizeHints.height != event.xconfigure.height)
+      {
+         sizeHints.width = event.xconfigure.width;
+         sizeHints.height = event.xconfigure.height;
+         XSetWMNormalHints (xDisplay, xWindow, &sizeHints);
+      }
       redraw = true;
       break;
    case ReparentNotify:
```

**Comment by brandoninvergo** [comment]
I can confirm that this patch resolves the problem. I will point the StumpWM maintainers at your comment so they can also look into it on their end.
Thanks for all your help in pinning this down!
