### ISSUE TITLE
No redraw on window resize

### ISSUE THREAD

**Issue by AftershockGT** [tomszilagyi/zutty#44]
A few small things that I have noticed using Zutty as my main terminal emulator.

The text displayed by Zutty is not redrawn when the terminal is resized, for instance if you have the result of a cat command and you resize the window, any text that is cutoff will remain cutoff if you undo the resize, it also won't wrap as expected to dodge the window edge. It does not seem to affect vim.
#### Steps to reproduce:
1. Cat a file then resize the window and try to hide some of the text
2. Text is not wrapped, undo the resize and the text will now be missing.

If I switch workspaces away from Zutty and then immediately return to it, it often displays blank for a few seconds before returning to normal. I could only get this to occur on DWM, it seemed fine on Gnome.

There seems to quite a few flickering issues at various times though all minor.

I'm really enjoying this terminal though seems like a good alternative to the others so far.

**Comment by tomszilagyi** [comment]
If you resize the terminal to be smaller, stuff that gets off-screen (to the right of the right edge) is lost, and won't magically re-appear if you subsequently make the window larger. Similarly, there is no post-hoc reformatting of already rendered terminal output (even if it was just a dumb listing). Zutty is a terminal, not a word processor.

The blank display seems like a separate issue, feel free to elaborate or open a better equipped bugreport for that (I don't see any such issue, so I need data). I invite you to run Zutty with debug output on, add some instrumentation (debug printouts) for X Expose and ConfigureNotify events, and see if the blanks are due to the window manager not sending those events on the Zutty window getting uncovered, or Zutty not responding appropriately to them. Maybe Zutty would also need to trigger a redraw on MapNotify (currently not the case), but that is not how I read the relevant specs. But you could see if that helps.

Completely unsure what you mean by flickering issues, please be much more specific.
