### ISSUE TITLE
Slow startup when using fonts with large charset.

### ISSUE THREAD

**Issue by PaulBonnot** [tomszilagyi/zutty#45]
Hello, I'm starting to use Zutty as my main terminal coming from st, and I noticed that the startup of the program is slower than st, which takes about 40ms to start on my machine against around 180ms for Zutty.

I investigated the issue and it seems that the main culprit is the function `FT_Load_Char()` in `font.cc`. It is called once for each character supported by the font for every style (regular/bold/italic/bolditalic). This function takes around 10µs in average on my computer. I use the Hack font patched with some nerdfonts, which means I have more than 3000 characters per style, so each style takes around 33ms to load, so loading all the font takes around 130ms.

The delay is quite noticeable since I tend to frequently fire up a new terminal.

Would it be possible to only load the most used characters (the 128 first) at startup, and then load the rest of the caracters in the cache only when needed ? That would have a small impact on latency but I think the tradeoff is reasonable. At least it could be a configurable option.

**Comment by tomszilagyi** [comment]
Interesting perspective, thanks for investigating and reporting. I never thought the one-time cost of up-front font rendering would be problematic to anyone (and I am really used to laggy terminals primarily due to slow networks), but a noticeably long start-up time is a valid concern. This will be easier to tackle once there is a path to do run-time updates to the font data (atlas and mapping textures) stored in GL memory. That would be necessary first and foremost if I wanted to support run-time font changes (e.g., increase/decrease font size with a hotkey, or similar) which is arguably more important than shaving off some startup time, but would open the door to a reasonable implementation of what you describe. Another option is to cache the aforementioned font-specific constant binary data (stored into GL) on disk somewhere (~/.config/zutty/<hash-of-font-settings>) and load it from there for repeated invocations with the same font settings (this would be easier to do in the short term, but I do not really like it).

In the meantime, you have a few options:
- use (or create) a font with less characters (do you use all 3000 of them?)
- do not start a new terminal all the time (I usually (re)start one every couple weeks, and use it to display my almost-forever tmux session in it)

**Comment by PaulBonnot** [comment]
I thought about patching the font with only the glyphs that I use but it can be a bit tedious to maintain, especially if I want to switch fonts.
But you are right that I launch a new terminal too often, I use a tiling WM so the mapping to Super+Enter is so easy to do that I use it all the time.
Anyway it is not a big deal to me, I just thought that the startup time can also be an interesting metric, although if you keep the same terminal all the time it really is unsignificant.

I also wanted to say that I like your project and the way you present it. A lot of time programs on Github are presented as fast without much of an explanation (GPU accelerated sounds good but doesn't mean much by itself !), and sometimes without even some data to back it up. Seeing a clear and detailed presentation of the program is quite refresing and make people more inclined to engage with it.
