### ISSUE TITLE
better error message for systems without compute shaders

### ISSUE THREAD

**Issue by mones** [tomszilagyi/zutty#84]
Hi Tom,

There is a bug report on Debian BTS about a user whose system doesn't run zutty¹ because it doesn't support compute shaders. So far, so good. The problem is that the error reported by zutty is kinda cryptic, and doesn't really hint the user about the real cause. And what it's even worse IMHO: it looks like there is some error on zutty's shader code.

I've made a very simple patch² trying to address this which you may add as is, or perhaps improve, as my knowledge about OpenGL is nearly zero, and I feel there's probably better methods to do it.

Thanks in advance and best regards,

¹ https://bugs.debian.org/1014080
² https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=1014080;filename=check_gl_extensions.patch;msg=22

**Comment by tomszilagyi** [comment]
I looked at your patch and tested it. On my system this breaks Zutty right away, because there is no extension with "compute" in it listed under GL_EXTENSIONS. Do not ask me why, I guess it's not an extension. But I'm afraid the right solution is a little trickier than this.

I am generally not bothered by the behaviour of Zutty on systems that are clearly insufficient to run it (the requirement for compute shaders and the minimum OpenGL ES version should be evident to anyone, as it is clearly and loudly advertised). I am also not interested in putting precious time into further researching this non-issue. (A better error message will not enable them to run Zutty, they will be in the exact same place.) 

If I load an OS install image into a machine that does not run that OS, I do not expect a great error message. Some garbled crap, a crash, or a cryptic error is what I would expect. People unable to run Zutty should feel less entitled to great error messages (they are free - and welcome - to think that Zutty is buggy, if that makes them feel better).

From my perspective, this is an utter and pure waste of time.

**Comment by mones** [comment]
Ok, I understand your that, and also wasn't expecting my tiny patch was going to work everywhere, so thanks for confirming it's not very useful :smile: 

Perhaps other simpler approach could be more adequate and less time-wasting that investigating how to detect compute shaders. For example, what if upon faling compiling shader x code, a message is added to the current error saying "Does your system support x shaders?".

Pretty simple and it can point the user into the right direction. What do you think?

**Comment by tomszilagyi** [comment]
I don't need or want to point people in the right direction.

There is no "pretty simple" approach that would leave everyone happy. Next thing will be someone complaining (as it has in fact already happened) that it's an abort (program crash - oh the horror!) and not a clean exit.

**Comment by mones** [comment]
Well, wasn't pretending to make everybody happy, I'm aware that's not possible.
Neither was trying to complain, it was simply a suggestion to improve zutty's output on those cases.
Sorry if it looked that way :worried: and thanks for your time.
